### ISSUE TITLE
QUESTION: checking exit status of process

### ISSUE THREAD

**Issue by hectorvs-gxg** [thuehlinger/daemons#33]
Ok, so, I'm trying to run a daemon like so:

```
Daemons.run_proc("some_process.rb") do
   raise "I FAILED" 
end
```

when I do:

```
ruby some_process.rb start
echo $?
```

the echo returns a success 0 code instead of 1. 
I've also tried to explicitly do an `exit 1`, but still, the return code is 0.

What is the correct way to do error checking?
Thanks!

**Comment by thuehlinger** [comment]
It is in the nature of the daemonization process that the starting process looses control of the daemon. Therefore keeping track of a daemon exiting with return code != 0 is not possible by the means offered by daemons. 

So what is happening in your script is that the script create a new daemon to run the proc and then exists immediately (with exit code 0, since it was able to successfully create a new daemon). The proc then starts within the new daemon, but raises the exception and then exists with return code 1 without being noticed.

However, there is a monitor functionality in daemons that periodically checks whether the spawned daemons are still alive, and if not restarts them (see documentation for the :monitor option).

**Comment by hectorvs-gxg** [comment]
Ok, I understand. 

From what I could gather, the `monitor: true` option will create a separate process that's watching my spawned proc, if the spawned proc fails, the monitor will attempt to restart it. This is good functionality, but I need my users to know if the process didn't start correctly and if so, why.

Given the nature of the daemonization process, I came up with a workaround. 

Basically, I'll call the `ruby my_proc.rb start` command and immediately run the `ruby my_proc.rb status` command. If the process is not running, the user will know to go check the logs for `my_proc.rb` that will contain the bactrace and other information.

Tt's not the most elegant solution, but it's a good compromise.

thanks for your help!
